/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlongamentoRouteImport } from './routes/alongamento'
import { Route as ApoioRouteImport } from './routes/apoio'
import { Route as CasaRouteImport } from './routes/casa'
import { Route as CasaConversaRouteImport } from './routes/casa-conversa'
import { Route as CasaRelaxarRouteImport } from './routes/casa-relaxar'
import { Route as LevantarCaixasRouteImport } from './routes/levantar-caixas'
import { Route as NutricaoRouteImport } from './routes/nutricao'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlongamentoRoute = AlongamentoRouteImport.update({
  id: '/alongamento',
  path: '/alongamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoioRoute = ApoioRouteImport.update({
  id: '/apoio',
  path: '/apoio',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaRoute = CasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaConversaRoute = CasaConversaRouteImport.update({
  id: '/casa-conversa',
  path: '/casa-conversa',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaRelaxarRoute = CasaRelaxarRouteImport.update({
  id: '/casa-relaxar',
  path: '/casa-relaxar',
  getParentRoute: () => rootRouteImport,
} as any)
const LevantarCaixasRoute = LevantarCaixasRouteImport.update({
  id: '/levantar-caixas',
  path: '/levantar-caixas',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricaoRoute = NutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alongamento': typeof AlongamentoRoute
  '/apoio': typeof ApoioRoute
  '/casa': typeof CasaRoute
  '/casa-conversa': typeof CasaConversaRoute
  '/casa-relaxar': typeof CasaRelaxarRoute
  '/levantar-caixas': typeof LevantarCaixasRoute
  '/nutricao': typeof NutricaoRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alongamento': typeof AlongamentoRoute
  '/apoio': typeof ApoioRoute
  '/casa': typeof CasaRoute
  '/casa-conversa': typeof CasaConversaRoute
  '/casa-relaxar': typeof CasaRelaxarRoute
  '/levantar-caixas': typeof LevantarCaixasRoute
  '/nutricao': typeof NutricaoRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alongamento': typeof AlongamentoRoute
  '/apoio': typeof ApoioRoute
  '/casa': typeof CasaRoute
  '/casa-conversa': typeof CasaConversaRoute
  '/casa-relaxar': typeof CasaRelaxarRoute
  '/levantar-caixas': typeof LevantarCaixasRoute
  '/nutricao': typeof NutricaoRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alongamento'
    | '/apoio'
    | '/casa'
    | '/casa-conversa'
    | '/casa-relaxar'
    | '/levantar-caixas'
    | '/nutricao'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alongamento'
    | '/apoio'
    | '/casa'
    | '/casa-conversa'
    | '/casa-relaxar'
    | '/levantar-caixas'
    | '/nutricao'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/alongamento'
    | '/apoio'
    | '/casa'
    | '/casa-conversa'
    | '/casa-relaxar'
    | '/levantar-caixas'
    | '/nutricao'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlongamentoRoute: typeof AlongamentoRoute
  ApoioRoute: typeof ApoioRoute
  CasaRoute: typeof CasaRoute
  CasaConversaRoute: typeof CasaConversaRoute
  CasaRelaxarRoute: typeof CasaRelaxarRoute
  LevantarCaixasRoute: typeof LevantarCaixasRoute
  NutricaoRoute: typeof NutricaoRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alongamento': {
      id: '/alongamento'
      path: '/alongamento'
      fullPath: '/alongamento'
      preLoaderRoute: typeof AlongamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoio': {
      id: '/apoio'
      path: '/apoio'
      fullPath: '/apoio'
      preLoaderRoute: typeof ApoioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa': {
      id: '/casa'
      path: '/casa'
      fullPath: '/casa'
      preLoaderRoute: typeof CasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa-conversa': {
      id: '/casa-conversa'
      path: '/casa-conversa'
      fullPath: '/casa-conversa'
      preLoaderRoute: typeof CasaConversaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa-relaxar': {
      id: '/casa-relaxar'
      path: '/casa-relaxar'
      fullPath: '/casa-relaxar'
      preLoaderRoute: typeof CasaRelaxarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levantar-caixas': {
      id: '/levantar-caixas'
      path: '/levantar-caixas'
      fullPath: '/levantar-caixas'
      preLoaderRoute: typeof LevantarCaixasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricao': {
      id: '/nutricao'
      path: '/nutricao'
      fullPath: '/nutricao'
      preLoaderRoute: typeof NutricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlongamentoRoute: AlongamentoRoute,
  ApoioRoute: ApoioRoute,
  CasaRoute: CasaRoute,
  CasaConversaRoute: CasaConversaRoute,
  CasaRelaxarRoute: CasaRelaxarRoute,
  LevantarCaixasRoute: LevantarCaixasRoute,
  NutricaoRoute: NutricaoRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
