/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlongamentoRouteImport } from './routes/alongamento'
import { Route as ApoioRouteImport } from './routes/apoio'
import { Route as NutricaoRouteImport } from './routes/nutricao'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlongamentoRoute = AlongamentoRouteImport.update({
  id: '/alongamento',
  path: '/alongamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoioRoute = ApoioRouteImport.update({
  id: '/apoio',
  path: '/apoio',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricaoRoute = NutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alongamento': typeof AlongamentoRoute
  '/apoio': typeof ApoioRoute
  '/nutricao': typeof NutricaoRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alongamento': typeof AlongamentoRoute
  '/apoio': typeof ApoioRoute
  '/nutricao': typeof NutricaoRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alongamento': typeof AlongamentoRoute
  '/apoio': typeof ApoioRoute
  '/nutricao': typeof NutricaoRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alongamento' | '/apoio' | '/nutricao' | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alongamento' | '/apoio' | '/nutricao' | '/api/chat'
  id: '__root__' | '/' | '/alongamento' | '/apoio' | '/nutricao' | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlongamentoRoute: typeof AlongamentoRoute
  ApoioRoute: typeof ApoioRoute
  NutricaoRoute: typeof NutricaoRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alongamento': {
      id: '/alongamento'
      path: '/alongamento'
      fullPath: '/alongamento'
      preLoaderRoute: typeof AlongamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoio': {
      id: '/apoio'
      path: '/apoio'
      fullPath: '/apoio'
      preLoaderRoute: typeof ApoioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricao': {
      id: '/nutricao'
      path: '/nutricao'
      fullPath: '/nutricao'
      preLoaderRoute: typeof NutricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlongamentoRoute: AlongamentoRoute,
  ApoioRoute: ApoioRoute,
  NutricaoRoute: NutricaoRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
